language: python
python:
  - "3.7-dev"
services: redis-server
cache: pip
install:
  - pip install pycodestyle
  - pip install -r requirements.txt
script:
  - pycodestyle *.py
  - REDIS_HOST=127.0.0.1 python -m unittest discover .

