version: '3'
services:
  redis:
    image: redis
  nginx:
    image: nginx
    depends_on:
      - app
    volumes:
      - socketvolume:/sockets
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mastermind.fcgi:/mastermind.fcgi
    ports:
      - 8080:8080
  app:
    image: crunis/mastermind
    depends_on:
      - redis
    volumes:
      - socketvolume:/sockets
volumes:
  socketvolume: